### ISSUE TITLE
blank page on module

### ISSUE THREAD

**Issue by scorpio2k2** [mwaldmueller/icingaweb2-module-oncall#1]
![oncall](https://cloud.githubusercontent.com/assets/915081/9574642/3ad26e4a-4fd1-11e5-82b9-f75a9d84da3e.PNG)
after module activation the module page is blank.

**Comment by mwaldmueller** [comment]
Hello,

thanks for your issue. The default pattern for users in the initial commit was set to "test*", so if there aren't any users beginning with this pattern you'll get a blank page. This could be changed in "application/forms/OncallForm.php".

In the redesigned version from today there's a configuration tab where the search pattern (default: "user-*") and the OnCall user (default: "icingaadmin") can be changed.


Best regards
Markus
